export const projectData = [
  {
    id: "001",
    imageUrl: "/assets/Hubolt/img1.jpg",
    header: "Hubolt - Design Concept",
    year: "2018 - 2019",
    descColor: "white",
    projectImages: [
      "/assets/Hubolt/img1.jpg",
      "/assets/Hubolt/img3.jpg",
      "/assets/Hubolt/img4.jpg",
      "/assets/Hubolt/img5.jpg",
      "/assets/Hubolt/img6.jpg",
      "/assets/Hubolt/img7.jpg",
      "/assets/Hubolt/img8.jpg",
      "/assets/Hubolt/img2.jpg",
    ],
    link: "",
    description:
      'Hubolt is an exclusive gaming platform that allows its users to play unique video games from their smartphone. Each game conveys specific emotion and feelings with each image, sound and colour.<br /><br /><p class="desc-heading">Home:</p>Easy, intuitive and personalized depending on your taste and interest is what Hubolt does with the first contact through the home. Without much effort you will be able to access the function that 90% of people need.<br /><br /><p class="desc-heading">Social:</p>Talk to friends while playing, join multiplayer games with your friends and much more. In Hubolt you can have fun with your friends and live unforgettable experience with them in your favorite games.<br /><br /><p class="desc-heading">Play and talk with friends:</p>Audio rooms allow you to create a space with friends, see what they are playing, join their games, and most importantly enjoy it.<br /><br /><p class="desc-heading">Game Library:</p>All your games in one place, resume your games from where you left off, access your games effortlessly and add favorite games.<br /><br /><p class="desc-heading">Profile:</p>You will be able to see and even show off your game status, see your trophy, compare your trophies with friends, change your status if you dont want to disturbed on the other hand you want everyone to see that you are ready to play.',
  },
  {
    id: "002",
    imageUrl: "/assets/EKORA/IMG_20230212_145344.JPG",
    header: "EKORA",
    year: "2017",
    descColor: "black",
    projectImages: [
      "/assets/EKORA/IMG_20230212_145344.jpg",
      "/assets/EKORA/IMG_20230212_145427.jpg",
      "/assets/EKORA/IMG_20230212_145523.jpg",
      "/assets/EKORA/IMG_20230212_145822.jpg",
      "/assets/EKORA/IMG_20230212_145855.jpg",
      "/assets/EKORA/IMG_20230212_145942.jpg",
      "/assets/EKORA/IMG_20230212_150016.jpg",
      "/assets/EKORA/IMG_20230212_150107.jpg",
      "/assets/EKORA/IMG_20230212_150219.jpg",
      "/assets/EKORA/IMG_20230212_150252.jpg",
      "/assets/EKORA/IMG_20230212_150329.jpg",
    ],
    link: "",
    description:
      "Veggie is an app where you can find a help guide for those who are vegan but also for those who are taking their first step in a vegan lifestyle. On this platform you will find vegan recipes, from easy and particular recipes, from easy and parctical recipes to more complex recipes, you will find the most varied information about a vegan lifestyle where you will be able to clarify all your doubts and lesrn new things.<br /><br />This application that focuses mainly on veganism. It aims to promote veganism and makes it easy to find recipes and you can also post and share recipes that you know of on the app.<br /><br />Veganism is the practice of abstaining from the use of animal products- particularly in the diet and an associated philosophy that rejects the commodity status of animals.[c] An individual who follows the diet or philosophy is known as a vegan<br /><br /><p class='desc-heading'>Context:</p>I personally know a lot of people that are trying to go vegan but the fear of if they are going to be eating well and how to know how to make vegan food is stopping them from living their dream. There are misconceptions that being vegan is difficult.<br /><br />For sure the vegan diet is definitely different from what most people eat which makes finding recipes more difficult than usual. Many also see veganism as in accessible, too expensive or boring.<br /><br />This app is designed to make cooking easy for vegan people too and also to share recipes with each other (Anyone who uses the application can see it).<br /><br /><p class='desc-heading'>The experience:</p><p class='desc-heading'>Alluring on boarding experience:</p>I designed the on boarding in such a way that it informs users what the application is all about without having to get into the application. To describe the experience, a simple variation of self-explanatory images is utilized.<br /><br /><p class='desc-heading'>Easy sign in and sign up process:</p>I created a very easy process that allows users to register with their own data and have their own account on the platform.<br /><br /><p class='desc-heading'>Exploring to find the right recipe for you:</p>Ekora is designed in such a way that even if you don't have enough time to type or have nothing in mind you can just explore and basically find different options for you that you can just select from Detailed information about each recipe. Most people that wants to use the app would like to see the detailed information about a recipe like the nutritional information and the rest so screens are provided for that. And there is also step by step mode<br /><br /><p class='desc-heading'>Search and filter:</p>Users can search for the recipe they want by just typing in something about the recipe it can be an ingredient or the name. I also added a filter or help narrow down the search and make it easier to find whatever the user desires.",
  },
  {
    id: "003",
    imageUrl: "/assets/Crid/IMG_20230212_192439.jpg",
    header: "Crid - Mobile App",
    year: "2017",
    projectImages: [
      "/assets/Crid/IMG_20230212_192247.jpg",
      "/assets/Crid/IMG_20230212_192315.jpg",
      "/assets/Crid/IMG_20230212_192351.jpg",
      "/assets/Crid/IMG_20230212_192416.jpg",
      "/assets/Crid/IMG_20230212_192439.jpg",
      "/assets/Crid/IMG_20230212_192508.jpg",
      "/assets/Crid/IMG_20230212_192552.jpg",
      "/assets/Crid/IMG_20230212_192617.jpg",
      "/assets/Crid/IMG_20230212_192639.jpg",
      "/assets/Crid/IMG_20230212_192658.jpg",
    ],
    link: "",
    description:
      "Crid - mobile banking app is designed to simplify the transfer of money anywhere in the world, you can send money in just a few clicks.<br /><br />Mobile banking application where you can use it for the standard features. Protect your transaction so we will give you 100% service. You can use all our service, may your transaction be successful.<br /><br /><p class='desc-heading'>Home:</p>After registration, the user gets to the home screen, which contains the total balance, user cards, recent transactions.<br /><br /><p class='desc-heading'>Cards:</p>The user can interact with the cards 24/7. For example- connect a new card, hide an active a hidden card, delete a card as well as change the card order. There are deeper settings for each card separately.<br /><br /><p class='desc-heading'>Statistic:</p>The app has 7 categories (Product, Food & Health, Apparels, Transport, Internet, Shopping and Transfers) for which user can see statistics in a bar chart. There also a filter by date.",
  },
  {
    id: "004",
    imageUrl: "/assets/Dojo/IMG_20230212_193212.jpg",
    header: "DOJO - Youth Clothes brand",
    year: "2017",
    projectImages: [
      "/assets/Dojo/IMG_20230212_193212.jpg",
      "/assets/Dojo/IMG_20230212_193242.jpg",
      "/assets/Dojo/IMG_20230212_193310.jpg",
      "/assets/Dojo/IMG_20230212_193340.jpg",
      "/assets/Dojo/IMG_20230212_193403.jpg",
      "/assets/Dojo/IMG_20230212_193425.jpg",
      "/assets/Dojo/IMG_20230212_193458.jpg",
      "/assets/Dojo/IMG_20230212_193545.jpg",
      "/assets/Dojo/IMG_20230212_193624.jpg",
      "/assets/Dojo/IMG_20230212_193653.jpg",
    ],
    link: "",
    description:
      "DOJO - youth clothes brand<br />You choose freedom, independence and originality.<br />You’re thinking free from prejudice.<br />You decide what you want to wear.",
  },
  {
    id: "005",
    imageUrl: "/assets/Avati/IMG_20230213_010621.jpg",
    header: "Avati",
    year: "2017",
    projectImages: [
      "/assets/Avati/IMG_20230213_010621.jpg",
      "/assets/Avati/IMG_20230213_010652.jpg",
      "/assets/Avati/IMG_20230213_010730.jpg",
      "/assets/Avati/IMG_20230213_010753.jpg",
      "/assets/Avati/IMG_20230213_010836.jpg",
      "/assets/Avati/IMG_20230213_010901.jpg",
      "/assets/Avati/IMG_20230213_010924.jpg",
      "/assets/Avati/IMG_20230213_011001.jpg",
      "/assets/Avati/IMG_20230213_011040.jpg",
      "/assets/Avati/IMG_20230213_011105.jpg",
      "/assets/Avati/IMG_20230213_011126.jpg",
      "/assets/Avati/IMG_20230213_011154.jpg",
      "/assets/Avati/IMG_20230213_011214.jpg",
      "/assets/Avati/IMG_20230213_011246.jpg",
      "/assets/Avati/IMG_20230213_011308.jpg",
      "/assets/Avati/IMG_20230213_011323.jpg",
    ],
    link: "",
    description:
      "Avati is a brand specialized in the manufacture of high-end, luxurious and morden home furniture and interior design. to be deistinguished in a large market such as the home interior and furniture industry.<br />We are a team of professionals in the feild of furniture production and interior design. we create dream interiors in different styles and implement our projects from the applications to the final touch.<br />So we came up with a unique typeface logo and created an icon for it that directly refectls the filed, It is an distinctive icon that you can highlight in the market in an unforgettable way amoung its targeted customers.<br />Avati is an high-quality interior architercture for residental and commercial spaces. They are looking for a balance between functionally, aesthetics, modernity and tradition, focusing on human experience with space.<br />We based identity on the cleanliness of the form, cost savings and content dispaly. Design, in its simpilicity, is elegant. With the class and sensitivity, it acts as the portfolio cuator - providing a full array of projects, at the same time guiding the audience and providing only the information needed.",
  },
  // {
  //   id: "004",
  //   imageUrl: "/assets/project-img.jpeg",
  //   header: "Basic UX",
  //   year: "2017",
  //   projectImages: [],
  //   link: "",
  //   description: "This is a sample description",
  // },
];
